types:
  __file: model.avsc

services:
    sendkafka:
      function: kafka_service.call
      return_type: ["null","string"]
      args:
          input: string

connector:
  input:
    - name: http
      type: http
    - name: kafka
      type: kafka
      brokers:
        - kafka-broker:9092
      topics:
        - in.test.topic
      group_id: kafka
      options:
        enable.auto.offset.store: "true"
        auto.offset.reset: "latest"
        enable.partition.eof: "false"
        security.protocol: "plaintext"

    - name: kafkaProcessor
      type: kafka
      brokers:
        - kafka-broker:49092
      topics:
        - in.test.processor
      group_id: kafka
      options:
        enable.auto.offset.store: "true"
        auto.offset.reset: "earliest"
        enable.partition.eof: "false"

        enable.ssl.certificate.verification: "false"
        security.protocol: "ssl"

        ssl.certificate.location: /tmp/keystore/kafka-broker1.cer.pem
        ssl.key.location: /tmp/keystore/kafka-broker1.key.pem
        ssl.ca.location: /tmp/truststore/ca-cert.pem
        ssl.key.password: secret
  
      routing_key: kafka_key

  output:
    - name: to_kafka
      type: kafka
      brokers:
        - kafka-broker:9092
      topic: out.test.topic
      group_id: kafka
      options:
        enable.auto.offset.store: "true"
        auto.offset.reset: "latest"
        enable.partition.eof: "false"
        security.protocol: "plaintext"

input_processor:
  handlers:
    - key: kafka_key
      function: kafka_service.processor
