version: '2.1'

services:
  datagrid:
    container_name: tdg2
    image: tdg:2.6.1-0-g1c1b9863
    ports:
      - "8080:8080"
      - "3301:3301"
    volumes:
      - "./keystore:/tmp/keystore/"
      - "./truststore:/tmp/truststore/"
    networks:
      - examplekafka

  zookeeper-server:
    container_name: zookeeper-server
    hostname: zookeeper-server
    image: 'bitnami/zookeeper:3.8.1'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - "./:/app/:rw"
    networks:
      - examplekafka

  kafka-broker:
    container_name: kafka-broker
    hostname: kafka-broker
    image: 'bitnami/kafka:3.0.0'
    ports:
      - "29092:29092"
      - "39092:39092"
      - "9092:9092"
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ZOOKEEPER_PROTOCOL=PLAINTEXT
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-server:2181

      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT,VAGRANT:SSL,TDGSSL:SSL
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:29092,VAGRANT://:39092,TDGSSL://:49092
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://:9092,EXTERNAL://localhost:29092,VAGRANT://localhost:39092,TDGSSL://:49092
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT

      - KAFKA_CFG_SSL_KEYSTORE_LOCATION=/bitnami/kafka/config/certs/kafka.keystore.jks
      - KAFKA_CFG_SSL_KEYSTORE_PASSWORD=secret
      - KAFKA_CFG_SSL_TRUSTSTORE_LOCATION=/bitnami/kafka/config/certs/kafka.truststore.jks
      - KAFKA_CFG_SSL_TRUSTSTORE_PASSWORD=secret
    volumes:
      - "./keystore/kafka-broker1.server.keystore.jks:/bitnami/kafka/config/certs/kafka.keystore.jks"
      - "./truststore/kafka.truststore.jks:/bitnami/kafka/config/certs/kafka.truststore.jks"
      - "./truststore/:/truststore:rw"
    networks:
      - examplekafka
networks:
  examplekafka:
    external: true
